### ISSUE TITLE
Set conda environment for a package

### ISSUE THREAD

**Issue by rashidrafeek** [JuliaPy/CondaPkg.jl#106]
I have a use case where I need to use an already existing conda environment. I have used the following set of environment variables to achieve this:
```
conda_env = "/path/to/conda_env"
ENV["CONDA_PREFIX"] = conda_env
ENV["JULIA_CONDAPKG_EXE"] = "mamba"
ENV["JULIA_CONDAPKG_BACKEND"] = "Current"
ENV["JULIA_CONDAPKG_ENV"] = "$conda_env/bin/conda"
```
This seems to work fine while working interactively. Is this possible to set this for a package, i.e, use a custom conda environment in a packge? I tried the following environment variables in the package, but CondaPkg seems to still use a new environment. 

Would there be some way I can use something like Preferences.jl to set the conda environment and use the set conda environment for later usage?

**Comment by cjdoris** [comment]
A package itself cannot set these settings - I have just added the reasoning to [FAQ in the README](https://github.com/JuliaPy/CondaPkg.jl#can-i-get-my-package-to-use-a-specific-conda-environment) because I've had this question a few times.

However, you have prompted me to finish some work I did ages ago to allow configuring the package with preferences. The new version is being registered, so soon you will be able to set preferences as [documented here](https://github.com/JuliaPy/CondaPkg.jl#preferences).

**Comment by rashidrafeek** [comment]
Thanks for the reply and adding the preferences support. I just tested setting preferences and it works great. This is exactly what I needed. As I needed to use an existing conda environment always for a package I am developing, I needed to somehow specify this for a package. AFAIK environment variables also cannot be set for a package and something like preferences was exactly what I needed. Thanks again for adding this! 

Closing as this issue is solved.
